account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from account.views import signup

urlpatterns=[
    url(r'^signup/$',signup,name="signup"),
    url(r'^login/$',auth_views.login,{'template_name':'login.html'},name="login"),
    url(r'^logout/$',auth_views.logout,{'next_page':'home'},name="logout"),
]

djangofirst/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todo.views import home,todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name='home'),
    url(r'^todos/$',todolist,name='todolist'),
    url(r'^todos/',include('todo.urls',namespace='todo')),
    url(r'^accounts/',include('account.urls'))
]

todo/urls.py
from django.conf.urls import url
from todo.views import contact,about,todolist,todoadd,service,home,todoedit,tododelete
urlpatterns=[
    url(r'^$',todolist,name='todolist'),
    url(r'^contact/$',contact,name='contact'),
    url(r'^add/$',todoadd,name='todoadd'),
    url(r'^service/$',service,name='service'),
    url(r'^about/$',about,name='about'),
    url(r'^edit/(?P<pk>\d+)/$',todoedit,name='todoedit'),
    url(r'^delete/(?P<pk>\d+)/$',tododelete,name='tododelete'),

    

    
    

]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Todo(models.Model):
    title=models.CharField(max_length=255)
    
    description=models.TextField()
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)


class Contact(models.Model):
    name=models.CharField(max_length=200)
    Sub=models.CharField(max_length=200)
    messg=models.TextField()
    email=models.CharField(max_length=50)

todo/forms.py
from todo.models import Contact, Todo
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        fields={"title","description","name","email"}
class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields={"name","Sub","messg","email"}

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
# Create your views here.



def signup(request):
    signupform=UserCreationForm(request.POST or None)
    if signupform.is_valid():
        signupform.save()
        username=signupform.cleaned_data.get('username')
        raw_password=signupform.cleaned_data.get('password1')
        user=authenticate(username=username, password=raw_password)
        login(request,user)
        return redirect('login')
    return render(request,'signupp.html',{'form':signupform})

todo/views.py
from wsgiref.util import request_uri
from django.shortcuts import render,redirect,get_object_or_404
from todo.forms import ContactForm, TodoForm
from todo.models import Todo
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')  
@login_required
def service(request):
    return render(request,'service.html')
@login_required
def contact(request): 
    Contactform=ContactForm(request.POST or None)
    if Contactform.is_valid():
        Contactform.save()
        return redirect("home")

    return render(request,'contact.html',{'form':Contactform})
@login_required
def todoadd(request):
    todoform=TodoForm(request.POST or None)
    if todoform.is_valid():
        todoform.save()
        return redirect("todolist")


    return render(request,'todoadd.html',{'form':todoform})
@login_required
def todolist(request):
    allfeedback=Todo.objects.all()
    return render(request,'todolist.html',{'todos':allfeedback})
@login_required
def todoedit(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    todoform=TodoForm(request.POST or None,instance=todo)
    if todoform.is_valid():
        todoform.save()
        return redirect("todolist")  
    return render(request,'todoadd.html',{'form':todoform}) 
@login_required
def tododelete(request,pk):   
    todo=get_object_or_404(Todo,pk=pk)
    if request.method=='POST':
        todo.delete()
        return render('todolist')
    return render(request,'tododelete.html',{'todo':todo})

templates/about.html
{% extends 'base.html'%}
{%block content%}
<head>
    <style>
        .img1{
            margin-bottom: 600px;
        }
        .con{
            background-color: rgb(249, 240, 230);
        }
       .butt{
        background-color: rgb(244, 236, 226);
        height:50px;
        width:200px;
        font-size:20px;



        }
        .butt:hover{
          background-color: black;
          color: aliceblue;

        }
        .con2{
          background-color: rgb(252, 244, 234);
          height:50%;
        }

        
    </style>
</head>
<div class="row">
    <div class="col-xs-6 col-md-5 img1">
      <a href="#" class="thumbnail">
        <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=656,h=682,fit=crop/ginza37pa0/img-Aok3lWLrBehKDwMQ.png" alt="...">
      </a>
    </div>
   
    <div class="col-xs-6 col-md-5">
        <h1 style="margin-left:200px;margin-top:100px;font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;font-size:80px;">How Ginza <br> came to be </h1><br><br>
      
        <p style="text-align:justify;margin-left:200px;">Ginza had an unconventional start as a restaurant. Originally opening as a pop-up event, our original aim was to showcase the unique culinary stylings of our head chef, Kabu Natsu.   </p><br><br><br>
       
      </div>
  </div>
  <div class="row">
    <div class="col-xs-3 col-md-5">
      <p style="margin-left:100px;">When it became clear that there was going to be continued interest in the eating experience we’d curated, we found a permanent location, expanded our menu, and began regular service. That was 5 years ago, and we’re still going strong today.</p><br><br><br>
      <p style="margin-left:100px;">Though we’ve come a long way from where we started (we’re up to 12 chefs and 10 servers on a normal evening), our focus has ever shifted. When you eat with us, you can expect to find new flavors, existing foods, and a sparkling evening.</p>
    </div>
    <div class="col-xs-3 col-md-5">
        <a href="#" class="thumbnail">
          <img style="margin-top:-200px;margin-left:100px" src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=656,h=825,fit=crop/ginza37pa0/OurStoryImg-mP44RxVMjnfeNDrZ.png" alt="...">
        </a>
      </div>
    
  </div>
  <br><br><br>
  <div class="container con2">
    <h1 style="text-align:center;padding:100px;font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;font-size: 50px;">Book a table</h1>
    <p style="text-align:center;">Reserving a table beforehand means less waiting. <br> Groups of 8 or more must reserve ahead of time.</p>
    <a href="http://127.0.0.1:8000/todos/contact/"><button class="butt" style="margin-left:550px;padding:10px">Book now</button></a>
  <br><br>  
  </div>
  {%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="icon" href="https://studygyaan.com/wp-content/uploads/2021/12/CicamXxN_400x400-1.jpg">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGOFIRST</title>
</head>


<body>
    {%include 'navbar.html'%}
    
    {%block content%}
    {%endblock%}
    {%include 'footer.html'%}
</body>
</html>

templates/contact.html
{% extends 'base.html'%}
{%block content%}
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
        form{
            margin-left:120px;
            margin-top:-50px;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            font-size:30px;
           }
        .column{
            display:table;
            width:33.33%;
        }
        .row{
            content:"";
            clear:both;
            
        }
        .link{
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            font-size:40px;
        }
        .map{
            border:8px solid rgb(188, 183, 247);
        }
        .cont{
            background-color: rgb(190, 195, 251);
        }
    </style>
</head>
<h1 style="margin-top:-350px;margin-left:80px;font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">Get In Touch With Us...</h1><br><br><br>
<form method="POST">
{%csrf_token%}
{{ form.as_p}}
<button style="margin-left:200px;" type="submit">Submit</button>
</form>
<img style="float:right;margin-top:-800px;margin-right:120px;height:40%;width:40%;" src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=656,h=892,fit=crop/ginza37pa0/OurStoryImg-mP44RxVMjnfeNDrZ.png" alt="">
<br><br><br><br><br>
<div>
    <div class="map" style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=206,%202nd%20Floor,%20Fortune%20Aura%20Business%20park%20(%20Kyro%20Building%201,%20Gurmeet%20Nagar,%20Bhanwarkua%20Main%20Road%20Landmark-%20Above%20Nexa%20Car%20Showroom,%20near%20Apple%20hospital,%20Indore,%20Madhya%20Pradesh%20452014+(livewire%20indore)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/sport-gps/">gps watches</a></iframe></div>
</div>
<br><br><br><br>
<div class="container cont">
<div style="margin-left:100px;padding:20px;" class="row"><div class="column"><h1 class="link"><i class="fa fa-clone" aria-hidden="true"></i>Contacts</h1>
    <a href=""><i class="fa fa-phone" >7697259416</i></a><br>
    <a href=""><i class="fa fa-envelope" ></i>livewire@gmail.com</a></div>
<div class="column"><h1 class="link"><i class="fa fa-map-marker" ></i>location</h1> 
    <a href=""><i class="fa fa-thumb-tack" aria-hidden="true"></i>livewire indore</a>

</div>
<div class="column"><h1 class="link"><i class="fa fa-clock-o" aria-hidden="true"></i>Hours</h1>
    <a href=""><i class="fa fa-calendar" aria-hidden="true"></i>Monday-Sunday</a><br>
    <a href=""><i class="fa fa-hourglass-half" aria-hidden="true"></i>10am-11pm</a>

</div>

</div>
</div>
<br><br><br><br><br><br>
{%endblock%}

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      footer{
       
        color:white;
        width:100%;
      }
     
    </style>
</head>
<body>
    <!-- Footer -->
<footer class="bg-dark text-center ">
    <!-- Grid container -->
    <div style="color:white;" class="container p-4 bg-dark">
  
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
       
  
  
      <!-- Section: Text -->
      
  
  
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            
            <h5 class="text-uppercase"><i class="fa fa-paper-plane" aria-hidden="true"></i>Links</h5>
  
            <ul class="list-unstyled mb-0 ff">
              <li>
                <a href="http://127.0.0.1:8000/todos/service/" class="text-light">Menu </a>
              </li>
              <li>
                <a href="http://127.0.0.1:8000/todos/about/" class="text-light">About</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase"><i class="fa fa-clone" aria-hidden="true"></i>Contact</h5>
  
            <ul class="list-unstyled mb-0 ff">
              <li>
                <a href="#!" class="text-light">7697259416</a>
              </li>
              <li>
                <a href="#!" class="text-light">livewire@gmail.com</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase"><i class="fa fa-clock-o" aria-hidden="true"></i>Hours</h5>
  
            <ul class="list-unstyled mb-0 ff">
              <li>
                <a href="#!" class="text-light">Monday - Sunday</a>
              </li>
              <li>
                <a href="#!" class="text-light">10 am - 10 pm</a>
              </li>
              
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase"><i class="fa fa-map-marker" aria-hidden="true"></i>Location</h5>
  
            <ul class="list-unstyled mb-0 ff">
              <li>
                <p class="text-light" style="text-align:justify;">LIVEWIRE INDORE
                  #206, 2nd Floor, Fortune Aura Business park ( Kyro Building 1, Gurmeet Nagar, Bhanwarkua Main Road Landmark- Above Nexa Car Showroom, near Apple hospital, Indore, Madhya Pradesh 452014</p>
              </li>
              <li>
                
              </li>
              
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
  
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2020 Copyright:
      <a class="text-light" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
</body>
</html>

templates/frontend/html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    <h1>my name is akshay</h1>
    <p>hello mam good afternoon</p>
    <a href="https://www.facebook.com/">facebook</a>
    <img src="https://img.freepik.com/free-vector/education-horizontal-typography-banner-set-with-learning-knowledge-symbols-flat-illustration_1284-29493.jpg?w=2000
    ">
    <form>
        <label>Name</label>
        <input type="text" placeholder="name"><br>
        <label>Last Name</label>
        <input type="text" placeholder="last name"><br>
        <label>D.O.B</label>
        <input type="date" ><br>
        <label>E-mail</label>
        <input type="email"><br>
        <button>submit</button>
    </form>
    <table>
        <tr>
            <th>s.no</th>
            <th>name</th>
            <th>age</th>
            <th>address</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Akshay</td>
            <td>23</td>
            <td>indore</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Nikhil</td>
            <td>23</td>
            <td>bhopal</td>
        </tr>

    </table>
    <ol>
        <li>nikhil</li>
        <li>Akshay</li>
        <li>ranjana</li>
    </ol>
    <ul>
        <li>Python</li>
        <li>Django</li>
        <li>datascience</li>
    </ul>
    <dl>
        <dt>apple</dt>
        <dd>good for health</dd>
    </dl>
    
    <marquee>hello mam</marquee>
    <iframe width="640" height="360" src="https://www.youtube.com/embed/aLHSjafb2K4" title="Motu Patlu | मोटू पतलू S1 | Remote Control | Episode 250 Part 1 | Download Voot Kids App" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</body>
</html>

templates/frontend/newfilter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>revision</title>
</head>
<body>
    <input id="search" type="text" placeholder="search here">
    <p>find the word from list</p>

    <ol id="list">
        <li>Akshay</li>
        <li>nikhil</li>
        <li>livewire</li>
        <li>django</li>
        <li>mernstack</li>
        <li>python</li>
    </ol>
    <script>
        $(document).ready(function(){
            $("#search").on("keyup",function(){
                var x=$(this).val().toLowerCase();
                $("#list li").filter(function(){
                    $(this).toggle($(this).text().toLowerCase()
                    .indexOf(x)>-1)
                });
            });
        });
    </script>
</body>
</html>

templates/frontend/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@500&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
     *{
  padding: 0;
  margin: 0;
  outline: 0;
  font-family: 'IBM Plex Sans', sans-serif;
}
body {
    height: 100vh;
    width: 100vw; 
    overflow: hidden;
}
.content {
  width: 80%;
  margin: 50px auto;
}
h1 {
  text-align: center;
}
.form {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  width: 100%;
  max-width: 320px;
  height: 50vh;
}
input#keyword {
  font-size: 18px;
  padding: 10px 20px;
  outline: 0;
  border: 1px solid #0f62fe;
  width: auto;
}
span.highlight {
  color: red;
  text-shadow: 0 1px 1px red;
}

    </style>
</head>
<body>
    <div class="content">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.      </p>
      </div>
      <h1>Find the word in paragraph</h1>
  
      <div class="form">
        <input type="text" id="keyword" class="form_control" placeholder="Search...">
      </div>
  
      <script>
        function textFind(keyword) {
          if(keyword) {
            var content = $("p").text();
            var searchText = new RegExp(keyword, "ig");
            var matches = content.match(searchText);       
  
            if(matches) {
              $("p").html(content.replace(searchText, function(match){
                return "<span class='highlight'>"+match+"</span>";
              }));
            }else {
              $('.highlight').removeClass('highlight');
            }
          }else{
            $('.highlight').removeClass('highlight');
          }
        }
        $(document).ready(function(){
          $('#keyword').on('keyup', function(){
            textFind($(this).val());
          })
        });
      </script>
</body>
</html>

templates/logout.html
{% extends 'base.html'%}
{%content block%}
{%endblock%}

templates/signup.html
{% extends 'base.html'%}
{%block content%}
<head>
    <style>
        .cont{
            margin-left:300px;
            margin-top:-580px;
        }
        .button{
            background-color: rgb(22, 155, 22);
            height:50px;
            width:200px;
            font-size:25px;
            color: aliceblue;
            margin-left:200px;
        }
        .button:hover{
            background-color: rgb(24, 223, 24); ;
        }
        .butt{
            background-color: rgb(224, 32, 32);
            height:50px;
            width:200px;
            font-size:25px;
            color: aliceblue;
            

        }
        .butt:hover{
            background-color: red;

        }
    </style>
</head>
<div class="container cont">
       
    <h1><b> sign-up </b> </h1>
    <p>please fill in this form to create an account</p>
    
    <label for="user-name"><b>username</b></label><br>
    <input type="text" placeholder="enter your name" name="user-name" required><br><br>
    
    <label for="password"><b>password</b></label><br>
    <input type="password" placeholder="enter password" name="password" required><br><br>
    
    <label for=" password"><b>re-password</b></label><br>
    <input type="password" placeholder="confirm your password" name="passsword" required><br>
    
    <label>
        <input type="checkbox" checked="checked" name="remember">Remember me
    </label><br>
    <p>By creating an account you agree to our <a href="">Terms & privacy</a></p>
    <i style="margin-left:400px;" class="fa fa-twitter-square" aria-hidden="true"></i>
    <i  class="fa fa-facebook-official" aria-hidden="true"></i>
    <i class="fa fa-google-plus-square" aria-hidden="true"></i>
    <i class="fa fa-envelope" aria-hidden="true"></i>
    
    <br><br><br>
    
    </form>
    <button type="submit" class="button"name="signup">signup</button>
    <button type="button" class="butt" name="home"> Cancle</button>
    </div>
{%endblock%}

templates/todoadd.html
{% extends 'base.html'%}
{%block content%}
<head>
    <style>
        form{
            margin-top:200px;
            margin-left:200px;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
        }
    </style>

</head>

<h1 style="margin-top:-250px;margin-left:80px;font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">Share Your Valuable Feedback With Us...</h1>
<form method="POST">
{%csrf_token%}
{{ form.as_p}}
<button type="submit">Submit</button>
</form>
<img style="float:right;margin-top:-1000px;margin-right:100px;" src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=656,h=962,fit=crop/ginza37pa0/cust-A3QQRDJrPNTa3eWE.png" alt="">
<br><br><br><br>
{%endblock%}

templates/tododelete.html
{% extends 'base.html'%}
{%block content%}
<form method="post">
    {%csrf_token%}
    <p>Are You Sure?</p>
    <p>Yes I Want To Delete "{{todo.title}}"</p>
    <button type="submit" name="tododelete">Delete</button>
</form>
{%endblock%}

templates/todolist.html
{% extends 'base.html'%}
{% block content%}
<head>
    <style>
        .con5{
            background-color:rgb(207, 207, 230);
        }
        .row{
            content:"";
            clear: both;

        }
        .column{
            display:table;
            width:50% ;
        }
        .jump{
            margin-top:-750px;
        }

    </style>
</head>
<!-- <head>
    <style>
        table,th,tr,td{
            border:2px solid rgb(140, 152, 152);
            text-align: center;
            font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            
        }
        .feed{
            margin-left:300px;
            font-family: Georgia, 'Times New Roman', Times, serif;
            font-size:40px;
            color: rgb(47, 46, 46);
            margin-top:-700px;
        }

    </style>
</head>
<h1 class="feed">All Feedbacks</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Update/Delete</th>

        </tr>
    </thead>
    <tbody>
        {% for todo in todos %}
        <tr>
            <td>{{todo.title}}</td>
            <td>{{todo.description}}</td>
            <td>{{todo.name}}</td>
            <td>{{todo.email}}</td>
            <td>{{todo.created_at}}</td>
            <td>{{todo.updated_at}}</td>
            <td><a href="{% url 'todo:todoedit' todo.id%}"><button>Edit</button></a>
            <a href="{% url 'todo:tododelete' todo.id%}"><button>Delete</button></a></td>
        </tr>
        {%endfor%}
    </tbody>
</table>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> -->
<div id="table" class="row jump">
    <marquee style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;font-size:40px;background-color: rgb(207, 207, 247);" behavior="" direction="right">Reviewses </marquee>
    <div class="column"><img style="width:100%;height:530px" src="https://thumbs.dreamstime.com/b/blank-notebook-text-please-review-us-white-background-calculator-office-tools-blank-notebook-text-please-218660181.jpg" alt=""></div>
    <div class="column">
        <div class="container con5">
            {%for todo in todos%}
            <h4>{{todo.name}}</h4>
            
            <h4>{{todo.title}}</h4>
            <h4>{{todo.description}}</h4>
            <p>{{todo.created_at}}</p>
            <p>{{todo.updated_at}}</p>
            <a href="{%url 'todo:todoedit' todo.id%}"><button>Edit</button></a>
           <a href="{%url 'todo:tododelete' todo.id%}"> <button>delete</button></a>
            <hr><hr>
            {%endfor%}
        
        </div>
    </div>
</div>
<script>
    



function exportF(elem) {
  var table = document.getElementById("table");
  var html = table.outerHTML;
  var url = 'data:application/vnd.ms-excel,' + escape(html); // Set your html table into url 
  elem.setAttribute("href", url);
  elem.setAttribute("download", "export.xls"); // Choose the file name
  return false;
}

</script>
<button><a id="downloadLink" onclick="exportF(this)">Download into Excel</a></button>





{%endblock%}